// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function pad(msg) {
  var size = (msg.length + 8 | 0) + 1 | 0;
  while(size % 64 !== 0) {
    size = size + 1 | 0;
  };
  var length = msg.length;
  var bytes = Belt_Array.makeBy(size, (function (index) {
          if (index < length) {
            return msg.charCodeAt(index) | 0;
          } else if (index === length) {
            return 128;
          } else {
            return 0;
          }
        }));
  var va = (length << 3);
  for(var i = 0; i <= 7; ++i){
    Belt_Array.set(bytes, i + (size - 8 | 0) | 0, va & 255);
    va = (va >>> 8);
  }
  return bytes;
}

exports.pad = pad;
/* No side effect */
