// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ReCrypt_MD5_Process = require("./MD5/ReCrypt_MD5_Process.bs.js");
var ReCrypt_MD5_Preprocess = require("./MD5/ReCrypt_MD5_Preprocess.bs.js");

function make(message) {
  return ReCrypt_MD5_Process.make(ReCrypt_MD5_Preprocess.pad(message));
}

var Preprocess;

var Process;

exports.Preprocess = Preprocess;
exports.Process = Process;
exports.make = make;
/* No side effect */
