// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Bytes = require("bs-platform/lib/js/bytes.js");
var ReCrypt_Sha224_Process = require("./Sha224/ReCrypt_Sha224_Process.bs.js");
var ReCrypt_Sha224_Preprocess = require("./Sha224/ReCrypt_Sha224_Preprocess.bs.js");

function make(message) {
  var messageBytes = Bytes.of_string(message);
  return ReCrypt_Sha224_Process.make(ReCrypt_Sha224_Preprocess.pad(messageBytes));
}

var Preprocess = /* alias */0;

var Process = /* alias */0;

exports.Preprocess = Preprocess;
exports.Process = Process;
exports.make = make;
/* No side effect */
