// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Bytes = require("bs-platform/lib/js/bytes.js");
var ReCrypt_MD5_Process = require("./MD5/ReCrypt_MD5_Process.bs.js");
var ReCrypt_MD5_Preprocess = require("./MD5/ReCrypt_MD5_Preprocess.bs.js");

function make(message) {
  var messageBytes = Bytes.of_string(message);
  return ReCrypt_MD5_Process.make(ReCrypt_MD5_Preprocess.pad(messageBytes));
}

var Preprocess = /* alias */0;

var Process = /* alias */0;

exports.Preprocess = Preprocess;
exports.Process = Process;
exports.make = make;
/* No side effect */
