// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ReCrypt_Sha224_Process = require("./Sha224/ReCrypt_Sha224_Process.bs.js");
var ReCrypt_Sha224_Preprocess = require("./Sha224/ReCrypt_Sha224_Preprocess.bs.js");

function make(message) {
  return ReCrypt_Sha224_Process.make(ReCrypt_Sha224_Preprocess.pad(message));
}

var Preprocess;

var Process;

exports.Preprocess = Preprocess;
exports.Process = Process;
exports.make = make;
/* No side effect */
