// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ReCrypt_Sha512_Process = require("./Sha512/ReCrypt_Sha512_Process.bs.js");
var ReCrypt_Sha512_Preprocess = require("./Sha512/ReCrypt_Sha512_Preprocess.bs.js");

function make(message) {
  return ReCrypt_Sha512_Process.make(ReCrypt_Sha512_Preprocess.pad(message));
}

var Preprocess;

var Process;

exports.Preprocess = Preprocess;
exports.Process = Process;
exports.make = make;
/* No side effect */
