// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Char = require("bs-platform/lib/js/char.js");
var Bytes = require("bs-platform/lib/js/bytes.js");
var Caml_bytes = require("bs-platform/lib/js/caml_bytes.js");
var ReCrypt_Utils = require("./ReCrypt_Utils.bs.js");

function pad(msgBytes) {
  var size = msgBytes.length + 16 | 0;
  while(size % 128 !== 0) {
    size = size + 1 | 0;
  };
  var length = msgBytes.length;
  var bytes = Bytes.init(size, (function (index) {
          if (index < length) {
            return Caml_bytes.get(msgBytes, index);
          } else if (index === length) {
            return Char.chr(128);
          } else {
            return Char.chr(0);
          }
        }));
  return ReCrypt_Utils.toBytes((length << 3), bytes);
}

var Sha512 = {
  pad: pad
};

exports.Sha512 = Sha512;
/* No side effect */
