// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Char = require("bs-platform/lib/js/char.js");
var Int64 = require("bs-platform/lib/js/int64.js");
var $$String = require("bs-platform/lib/js/string.js");
var Caml_bytes = require("bs-platform/lib/js/caml_bytes.js");
var Caml_int64 = require("bs-platform/lib/js/caml_int64.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");

function int64_of_bytes(input, j) {
  var v = Int64.zero;
  for(var i = 0; i <= 7; ++i){
    var tmp;
    var exit = 0;
    var some;
    try {
      some = Caml_bytes.get(input, i + j | 0);
      exit = 1;
    }
    catch (exn){
      tmp = Int64.zero;
    }
    if (exit === 1) {
      tmp = Caml_int64.of_int32(some & 255);
    }
    v = Caml_int64.add(Caml_int64.lsl_(v, 8), tmp);
  }
  return v;
}

function toBytes(value, bytes) {
  var va = value;
  for(var i = 1; i <= 15; ++i){
    bytes[bytes.length - i | 0] = Char.chr(va & 255);
    va = (va >> 8);
  }
  return bytes;
}

function append32(hash, value, offset) {
  for(var j = 0; j <= 3; ++j){
    hash[j + offset | 0] = Char.chr((value >>> (24 - (j << 3) | 0)) & 255);
  }
  return /* () */0;
}

function append64(hash, value, offset) {
  for(var j = 0; j <= 7; ++j){
    hash[j + offset | 0] = Char.chr(Caml_int64.to_int32(Caml_int64.and_(Caml_int64.lsr_(value, 56 - (j << 3) | 0), /* int64 */[
                  /* hi */0,
                  /* lo */255
                ])));
  }
  return /* () */0;
}

function stringToHex(input) {
  var hex = "0123456789abcdef";
  var length = input.length;
  return $$String.init((length << 1), (function (index) {
                var $$char = Caml_string.get(input, index / 2 | 0);
                if (index % 2 === 0) {
                  return Caml_string.get(hex, ($$char >>> 4) & 15);
                } else {
                  return Caml_string.get(hex, $$char & 15);
                }
              }));
}

exports.int64_of_bytes = int64_of_bytes;
exports.append32 = append32;
exports.append64 = append64;
exports.toBytes = toBytes;
exports.stringToHex = stringToHex;
/* No side effect */
