// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var MD = /* alias */0;

var SHA1 = /* alias */0;

var SHA2 = /* alias */0;

exports.MD = MD;
exports.SHA1 = SHA1;
exports.SHA2 = SHA2;
/* No side effect */
