// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ReCrypt_Sha1_Process = require("./Sha1/ReCrypt_Sha1_Process.bs.js");
var ReCrypt_Sha1_Preprocess = require("./Sha1/ReCrypt_Sha1_Preprocess.bs.js");

function make(message) {
  return ReCrypt_Sha1_Process.make(ReCrypt_Sha1_Preprocess.pad(message));
}

exports.make = make;
/* No side effect */
