// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ReCrypt_Sha384_Process = require("./Sha384/ReCrypt_Sha384_Process.bs.js");
var ReCrypt_Sha384_Preprocess = require("./Sha384/ReCrypt_Sha384_Preprocess.bs.js");

function make(message) {
  return ReCrypt_Sha384_Process.make(ReCrypt_Sha384_Preprocess.pad(message));
}

exports.make = make;
/* No side effect */
