// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ReCrypt_Sha256 = require("./ReCrypt/ReCrypt_Sha256.bs.js");
var ReCrypt_Sha512 = require("./ReCrypt/ReCrypt_Sha512.bs.js");

var Sha256 = ReCrypt_Sha256;

var Sha512 = ReCrypt_Sha512;

exports.Sha256 = Sha256;
exports.Sha512 = Sha512;
/* No side effect */
