// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function k(t) {
  if (t >= 0 && t <= 19) {
    return 1518500249;
  } else if (t >= 20 && t <= 39) {
    return 1859775393;
  } else if (t >= 40 && t <= 59) {
    return -1894007588;
  } else if (t >= 60 && t <= 79) {
    return -899497514;
  } else {
    return 0;
  }
}

var initialHash = [
  1732584193,
  -271733879,
  -1732584194,
  271733878,
  -1009589776
];

exports.k = k;
exports.initialHash = initialHash;
/* No side effect */
