// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ReCrypt_MD5 = require("./ReCrypt/ReCrypt_MD5.bs.js");
var ReCrypt_Sha1 = require("./ReCrypt/ReCrypt_Sha1.bs.js");
var ReCrypt_Sha224 = require("./ReCrypt/ReCrypt_Sha224.bs.js");
var ReCrypt_Sha256 = require("./ReCrypt/ReCrypt_Sha256.bs.js");
var ReCrypt_Sha384 = require("./ReCrypt/ReCrypt_Sha384.bs.js");
var ReCrypt_Sha512 = require("./ReCrypt/ReCrypt_Sha512.bs.js");

var MD5 = {
  make: ReCrypt_MD5.make
};

var Sha1 = {
  make: ReCrypt_Sha1.make
};

var Sha224 = {
  make: ReCrypt_Sha224.make
};

var Sha256 = {
  make: ReCrypt_Sha256.make
};

var Sha384 = {
  make: ReCrypt_Sha384.make
};

var Sha512 = {
  make: ReCrypt_Sha512.make
};

exports.MD5 = MD5;
exports.Sha1 = Sha1;
exports.Sha224 = Sha224;
exports.Sha256 = Sha256;
exports.Sha384 = Sha384;
exports.Sha512 = Sha512;
/* No side effect */
