// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Char = require("bs-platform/lib/js/char.js");
var Bytes = require("bs-platform/lib/js/bytes.js");
var Caml_bytes = require("bs-platform/lib/js/caml_bytes.js");

function pad(msgBytes) {
  var size = (msgBytes.length + 16 | 0) + 1 | 0;
  while(size % 128 !== 0) {
    size = size + 1 | 0;
  };
  var length = msgBytes.length;
  var bytes = Bytes.init(size, (function (index) {
          if (index < length) {
            return Caml_bytes.get(msgBytes, index);
          } else if (index === length) {
            return Char.chr(128);
          } else {
            return Char.chr(0);
          }
        }));
  var va = (length << 3);
  for(var i = 1; i <= 15; ++i){
    bytes[bytes.length - i | 0] = Char.chr(va & 255);
    va = (va >> 8);
  }
  return bytes;
}

exports.pad = pad;
/* No side effect */
