// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Int32 = require("bs-platform/lib/js/int32.js");

function rotl(x, n) {
  return (x << n) | (x >>> (64 - n | 0)) | 0;
}

function change(x, y, z) {
  return x & y ^ Int32.lognot(x) & z;
}

function majority(x, y, z) {
  return x & y ^ x & z ^ y & z;
}

function parity(x, y, z) {
  return x ^ y ^ z;
}

function f(t, x, y, z) {
  if (t >= 0 && t <= 19) {
    return change(x, y, z);
  } else if (t >= 20 && t <= 39) {
    return parity(x, y, z);
  } else if (t >= 40 && t <= 59) {
    return majority(x, y, z);
  } else if (t >= 60 && t <= 79) {
    return parity(x, y, z);
  } else {
    return 0;
  }
}

exports.rotl = rotl;
exports.change = change;
exports.majority = majority;
exports.parity = parity;
exports.f = f;
/* No side effect */
